import { Task } from "@/components/tasks/Task";

export const tasks = [
  new Task(
    "1",
    "Skradnij godność i trunek Posejdona fajnego",
    "YELLOW descript ion3OW descri ption3 OW descript ion3OW descript ion3 OW descr iption3OW desc ription3OW descripti on3 OW description 3OW description3OW description3",

    false,
    false,
    false,
    false,
    "Adam Kośny",
    "1.03.2023",
    "Hubert Górski",
    "3.12.2023",
    4
  ),
  new Task(
    "2",
    "YELLOW title2",
    "YELLOW description3 OW description3OW description3 OW description3OW description3OW description3 OW description3OW description3OW description3",

    false,
    false,
    false,
    false,
    "",
    "",
    "",
    "",
    12
  ),
  new Task(
    "3",
    "YELLOW title3",
    "YELLOW description3OW description3 OW description3OW description3 OW descriription3OW description3OW description3",
    false,
    false,
    false,
    false,
    "",
    "",
    "",
    "",
    -15
  ),
  new Task(
    "4",
    "YELLOW title4",
    "YELLOW description3OW description3 OW description3OW description3 OW description3OW description3OW description3 OW description3OW description3OW description3",

    false,
    false,
    false,
    false,
    "",
    "",
    "",
    "",
    -2
  ),
  new Task(
    "5",
    "YELLOW title5",
    "YELLOW description3OW description3 OWon3 OW description3OW description3OW description3",

    false,
    false,
    false,
    false,
    "",
    "",
    "",
    "",
    -69
  ),
  new Task(
    "6",
    "YELLOW title6",
    "YELLOW description6",
    false,
    false,
    false,
    false,
    "",
    "",
    "",
    "",
    8
  ),
  new Task(
    "1",
    "YELLOW title1",
    "YELLOW description1",
    false,
    false,
    false,
    false,
    "",
    "",
    "",
    "",
    4
  ),
  new Task(
    "2",
    "YELLOW title2",
    "YELLOW description2",
    false,
    false,
    false,
    false,
    "",
    "",
    "",
    "",
    12
  ),
  new Task(
    "3",
    "YELLOW title3",
    "YELLOW description3",
    false,
    false,
    false,
    false,
    "",
    "",
    "",
    "",
    -15
  ),
  new Task(
    "4",
    "YELLOW title4",
    "YELLOW description4",
    false,
    false,
    false,
    false,
    "",
    "",
    "",
    "",
    -2
  ),
  new Task(
    "5",
    "YELLOW title5",
    "YELLOW description5",
    false,
    false,
    false,
    false,
    "",
    "",
    "",
    "",
    -69
  ),
  new Task(
    "6",
    "YELLOW title6",
    "YELLOW description6",
    false,
    false,
    false,
    false,
    "",
    "",
    "",
    "",
    8
  ),
];
